def p(g):
 d='[NGmDmKKPaiHSGmDmLLPgiZYGHnmPaimKBDSxFZZmPgimLCDYGmoVbtaVbtaVbrbhbtaVboVuSGmoVbcWVbcWVbsk8fbcWVboVuYGmaopatapataparmatapaocHSGmaopacWpacWpasg8fbacWpaocHYGmDmKBPaiHnSGmDmLCPgiZJYGnmDmKBPaiHSGnmDmLCPgiZYxbDmKKPaiHHSxbDmLLPgiZZYGjaDbharVarVarbjarVaDbhuSGjaDbhasVasVasW8fasVaDbhuYGnmPaimKKDnSxFZmPgimLLDnYGnmPaimKBDHSxFZmPgimLCDHYGmPaimKKDHSxFJmPgimLLDHYGmPaimKBDHnSxFJmPgimLCDHnYGmDmKrbhbBDHSGmDmLsk8fbCDHYGmaDhbarchbarchlchbarchbaDhuSGmaDhbaschbaschqqchbaschbaDhuYGjdoc5fdr5fdr5fla5fdr5fdoc5fuSGjdoc5fds5fds5fqqg5fds5fdoc5fuYGmoVbtaVbtaVdbVbtaVboVuSGmoVbcWVbcWVqkVbcWVboVuYGmDmBrcjdbapBDHSGmDmCscjqWpCDHYxlmDmKKPaiHnSxlmDmLLPgiZJYxbDmKBPaiHHnSxbDmLCPgiZZJYGHmPaimKBDnSxFZJmPgimLCDnYGjDbjrtjrtjclhrtjDbHSGjDbjstjstjsq8fstjDbHYxlmDmKBPaiHHSxlmDmLCPgiZZYGjaotjatatjatatjarbjatatjaotHSGjaotjacWtjacWtjasW8facWtjaotHYGjAo5fAta5fAta5fla5fAta5fAo5fuSGjAo5fAcW5fAcW5fqqg5fAcW5fAo5fuYGmaopatapatacjdbapatapaocHSGmaopacWpacWcjqWpacWpaocHYGjdochdtachdtachlchdtachdochuSGjdochdcWchdcWchqqchdcWchdochuYGHmPaimKKDSxFZJmPgimLLDYGjorhtarhtarhclhtarhorhuSGjorhcWrhcWrhsq8fcWrhorhuU]'
 m='JJZXNYU,XkgWthVT}Uz]TROSQ"RzeQicPMIN{"MCCLBBKjFJnnHxuGEbFAgEoiDspCrpBdaAy]za0yw[xv[w":vlnucbtcqscdrkkqcmpiiojlnjbmddlggkahjcci0fh8,ge[f],ebbd5,caab0,a'
 m=[[m[i:i+2],m[i+2]]for i in range(0,len(m),3)]
 for r in m:d=d.replace(r[1],r[0])
 d=eval(d)
 for k in d:
  if k['I']==g:g=k['O'];return g